[package]
name = "recursive-hash"
version = "0.1.2-rc.0"
authors = ["Yu Xiaosong <hammerklavier@139.com>"]
edition = "2024"
description = "A GUI/CLI tool for recursively hashing files in directories"

[profile.dev]

[profile.dev.package]
md-5 = { opt-level = 2 }
sha1 = { opt-level = 2 }
sha2 = { opt-level = 2 }

[profile.release]
lto = "thin"

[dependencies]
async-channel = "2.5"
clap = { version = "4.6", features = ["derive"] }
digest = "0.11"
env_logger = "0.11.10"
log = "0.4"
md-5 = "0.11"
sha1 = "0.11"
sha2 = "0.11"

[dependencies.gtk]
package = "gtk4"
version = "0.11"
optional = true
features = ["v4_14"]

[dependencies.adw]
package = "libadwaita"
version = "0.9"
optional = true
features = ["v1_4"]

[features]
default = []
gui = ["dep:gtk", "dep:adw"]
